// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agknizrjjljuxdhnywfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFna25penJqamxqdXhkaG55d2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTE5ODUsImV4cCI6MjA2MDcyNzk4NX0.apotkfEIRIiWiSwMLccjeINGsJyJLXLeBkhNwVMzGl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);